### ISSUE TITLE
SSH aliases are unknown to `et`

### ISSUE THREAD

**Issue by hemberger** [MisterTea/EternalTCP#58] opened 2017-08-10 00:39 UTC
First, let me say that EternalTCP solves my eternal frustrations with SSH. Thank you!

The only thing that seems to be missing is the ability to specify aliases (either by using aliases in `~/.ssh/config` or having a separate configuration file). I had hoped that the resolution to #31 would solve this issue, but it doesn't. I have tried the following.

In my `~/.ssh/config`:
```
host        MYALIAS
hostname    MYHOSTNAME
user        MYUSER
```
NOTE: `MYUSER` exists as a user on both the client and server machines.

Attempted commands:
`et MYUSER@MYHOSTNAME`: works!
`et MYHOSTNAME`: works!
`et MYUSER@MYALIAS`: fails
`et MYALIAS`: fails

Error message on failure:
`Could not make initial connection to MYALIAS: Could not connect to host`
In the log file with `-v` specified:
`E0809 17:12:48.327687 24144 TerminalClient.cpp:88] Connecting to server failed: Could not connect to host`

I would have assumed that, since ssh is used for the initial handshake, `MYALIAS` would work at this point (even if it failed later). I am very interested in this functionality, so I'd be happy to contribute a PR if you want to discuss how to add it.

**Comment by MisterTea** [comment] 2017-08-11 01:44
The issue is that ET uses ssh for the initial handshake but then it uses it's own protocol to start the connection.  The ET client doesn't know anything about your ssh_config file.

To fix this, you would need to write an ssh config parser and keep a mapping from alias to the actual hostname in the ET client.  If you do the first, I can do the second.

Here's the ssh config spec: https://www.ssh.com/ssh/config/
Here's an implementation of the spec in c: https://github.com/openssh/openssh-portable/blob/master/readconf.c

If you create some class that reads ssh_config files and provides any alias mappings in a PR, then I can do the rest.

**Comment by MisterTea** [comment] 2017-10-03 06:13
Fixed by https://github.com/MisterTea/EternalTCP/pull/64

**Closed by MisterTea** 2017-10-03 06:13 UTC
