### ISSUE TITLE
Multiple et connections

### ISSUE THREAD

**Issue by NikolasOliveira** [MisterTea/EternalTCP#21] opened 2017-03-27 23:04 UTC
Before I start attaching any logs as if there were a bug, let me first ask if this ticket should be a feature request: 
Should it currently be possible to connect from a client to a server multiple times with `et`?

I connect from my laptop to a desktop/VM located in my work office to do most of my work (hence things like `mosh`/`et` being so useful as I roam with my laptop) and in doing so I open a lot of shells to the remote machine. But currently if I open a second `et` connection my first connection exits.

**Comment by MisterTea** [comment] 2017-03-28 00:59
That's by design.  There's no et daemon that starts when your machine boots, so it spawns an et server when you connect.  You can't have multiple servers listening on the same port, so it kicks out other servers.
If you want multiple terminals, you should be using "tmux -CC" which lets you have multiple tabs and windows using the same connection.  Unfortuntely, only iTerm (mac only) and a fork of Terminator supports tmux -CC at the moment.
It may not be hard to allow multiple et connections.  I'll look into it and report back.  The issue is what to do when a client dies.  If the client reconnects and a new connection starts, then we need some way to clean up the old connections.  Mosh does this by warning you when there's a stale connection and letting the user kill it.

**Comment by NikolasOliveira** [comment] 2017-03-28 18:18
Thanks for the quick response @MisterTea!
I unfortunately don't use a terminal emulator that supports tmux -CC; further to that I use a tiled window manager that does all my tabbing, window organizing and tiling already and would like to avoid introducing yet another layer on top of that with tmux -CC if I can avoid it.

So as of now the `et` one connection limit is kind of a deal breaker for me :( 

Consider this an eager feature request for native support for multiple sessions with `et` :)
Even if it's as simple as `mosh`'s support for this, which isn't great as you mentioned, but a big step forward at least.

Cheers,
Niko

**Comment by MisterTea** [comment] 2017-03-28 18:33
Sure. I also don't like this limitation so I'll look into it and see if I
can find a simple way to make it happen

**Comment by MisterTea** [comment] 2017-04-04 21:27
Dupe of #20

**Closed by MisterTea** 2017-04-04 21:27 UTC
